# Generated by Django 4.0.5 on 2022-06-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('encounterType', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonIndex', models.IntegerField()),
                ('pokemonName', models.CharField(max_length=32)),
                ('pokemonEggGroup', models.ManyToManyField(to='PokedexAPI.egggroup')),
                ('pokemonEvolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evolution', to='PokedexAPI.pokemon')),
                ('pokemonLocation', models.ManyToManyField(to='PokedexAPI.location')),
                ('pokemonPrevolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prevolution', to='PokedexAPI.pokemon')),
                ('pokemonType', models.ManyToManyField(to='PokedexAPI.type')),
            ],
        ),
    ]
